apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: 2048-deployment
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: 2048-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
