---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: efs-provisioner
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: efs-provisioner
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: efs-provisioner
    version: 0.7.0
  values:
    efsProvisioner:
  # If specified, use this DNS or IP to connect the EFS
      dnsName: "10.132.201.79"
      efsFileSystemId: fs-5169d8b3
      awsRegion: us-east-1
      path: /
      provisionerName: example.com/aws-efs
      storageClass:
        name: efs
        isDefault: true
        gidAllocate:
          enabled: true
          gidMin: 40000
          gidMax: 50000
        reclaimPolicy: Delete
        mountOptions: [nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport]
    rbac:
      create: true
      serviceAccountName: ""
